### ISSUE TITLE
Cellphone screenshots not centering horizontaly on blog

### ISSUE THREAD

**Issue by David-mo** [inBeat/inbeat-website#90]
I added cellphone captures to my blog article:
https://www.inbeat.co/articles/finding-tik-tok-influencers/

Images are not centered:
![Screenshot_050220_123132_PM](https://user-images.githubusercontent.com/9886889/80869880-dc642d80-8c70-11ea-9152-0d8886f5621d.jpg)

They are centered on  the ghost.inbeat.co article link:
https://ghost.inbeat.co/finding-tik-tok-influencers/

**Comment by afunnydev** [comment]
Found the fix, will release on next push. FYI, the styling on ghost.inbeat.co is totally unrelated to the styling on inbeat.co. They don't share any code, since Ghost as it's own theme system (we are on the default theme). So, even if you see something centered ghost.inbeat.co, it don't mean it will be in inbeat.co. Maybe one day I can create a Ghost theme for our site that is the same as our website!
